---
- name: Execute Windows install playbooks
  hosts: windows
  gather_facts: true

  roles:
    - role: parchados_sul
      vars:
        controle: true
    - role: Bastionados
    - role: agents_sul
    - role: Regionais/{{ countries }}
      vars:
        controle_regionais: true
    - role: parchados_sul
      allow_duplicates: true    
    - role: Regionais/{{ countries }}
      allow_duplicates: true    
